[project]
name = "pin"
version = "2.6.12"
description = "A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives"
readme = "README.md"
license= "BSD-3-Clause"
dependencies = ["hpp-fcl", "cmeel-urdfdom", "cmeel-console-bridge", "cmeel-tinyxml"]

[project.urls]
homepage = "https://github.com/stack-of-tasks/pinocchio"

[build-system]
requires = [
    "cmeel[build]",
    "cmeel-boost",
    "cmeel-console-bridge",
    "cmeel-eigen",
    "cmeel-tinyxml",
    "cmeel-urdfdom",
    "cmeel-urdfdom-headers",
    "hpp-fcl",
    ]
build-backend = "cmeel.build"
build-number = 3
configure-args = [
    "-DBUILD_WITH_COLLISION_SUPPORT=ON",
    "-DBUILD_WITH_LIBPYTHON=OFF",
    "-DSUFFIX_SO_VERSION=OFF",
    ]
