name: Build pinocchio for Mac OS X/Linux via pip

on: [push, pull_request]

env:
    CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  pinocchio-pip:
    name: CI on ${{ matrix.os }} / python ${{ matrix.python-version }} with pip
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip
      - run: python -m pip install cmeel-urdfdom[build] hpp-fcl[build]
      - run: echo "CMAKE_PREFIX_PATH=$(python -m cmeel cmake)" >> $GITHUB_ENV
      - run: echo "LD_LIBRARY_PATH=$(python -m cmeel lib)" >> $GITHUB_ENV
      - run: cmake -B build -S . -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
      - run: cmake --build build
      - run: cmake --build build -t test
